name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Execute Katalon Studio project on Github Actions with No Cost
      uses: depapp/free-katalon-studio-github-actions@v2.8.4
      with:
        testSuitePath: 'Test Suites/Verify Operations'
        browserType: 'Safari'
        executionProfile: 'default'
