name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: FREE Katalon Studio Github Action
      uses: depapp/free-katalon-studio-github-actions@v2.8.1
      with:
        testSuitePath: 'Test Suites/Web/TS - Login'
        browserType: 'Chrome'
        executionProfile: 'default'
